apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "microapp-api"
  namespace: default
  labels:
    app:  "microapp-api"
spec:
  selector:
    matchLabels:
      app: "microapp-api"
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "microapp-api"
    spec:
      containers:
      - name:  microapp-api
        image: oluwatoseen/microapp-api
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name: "microapp-api"

---

apiVersion: v1
kind: Service
metadata:
  name: "microapp-api"
  namespace: default
spec:
  selector:
    app: "microapp-api"
  type: LoadBalancer
  ports:
  - name: "microapp-api"
    protocol: TCP
    port: 80

