name: Docker Image CI (API-Gateway)

on:
  push:
    branches: [ "main" ]
    path: ["zuul-api-gateway/**"]
  pull_request:
    branches: [ "main" ]
    path: ["zuul-api-gateway/**"]
              

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: oluwatoseen/microapp-api:latest
